### ISSUE TITLE
For spring-boot 3 the frontend of the example is not working

### ISSUE THREAD

**Issue by bartvl-xenit** [paulcwarren/spring-content-gettingstarted#198]
The endpoints that are used to load the filelist and to post a new file in the "complete" example with filesystem store, are pointing to /files/ and the last / should be omitted!

**Comment by paulcwarren** [comment]
I missed this Issue when you created it.  Apologies.  Getting started's have been upgraded to Spring Boot 3.3.2 today so I assume this issue is long resolved.  Please re-open if not.
