### ISSUE TITLE
File entity cannot be removed

### ISSUE THREAD

**Issue by cedricSarre** [paulcwarren/spring-content-gettingstarted#203]
Hello Paul.
I am currently developping a Web application based on Spring Content and I meet some difficulties to remove my entity from the DB.

My application is near from your "spring-content-with-rest" sub-test-module.
So I started this sub-module locally, I created a File entity from a POST request, but by trying to remove it by a `DELETE https://localhost:8080/files/<id>`, I met the same issue (404_NOT_FOUND) : the File entity is not removed from the DB.
When I tried to get the File entity, I also received à 404_NOT_FOUND.

I also modified the test class present in the "spring-content-with-rest" sub-module by adding the following tests in the `Context("with existing content"` part.
```java
It("should remove the file", () -> {
  given()
  .when()
  .delete("files/" + file.getId())
  .then()
  .statusCode(HttpStatus.SC_NO_CONTENT); // => return 204 that is not the same return code than by starting the application
});

It("should not found the file", () -> {
  given()
  .when()
  .get("files/" + file.getId())
  .then()
  .statusCode(HttpStatus.SC_NOT_FOUND);  // => return a 200 instead of a 404 as the File entity should have been removed.
});
```

One more thing, I am able to list all File entities (from `GET http://localhost:8080/files`), no issue regarding this part.

Did I miss something?

Thanks a lot and thanks for the great job done on Spring Content!

**Comment by paulcwarren** [comment]
Apologies that I did not see this (for over a year) but as per the PR I just created you have to specify `application/json` header to target the Spring Data Controllers (as shown), or configure Spring Content to ignore json content (but you might not want to do that.

I would highly recommend that you use the entity URL for entity operations (i.e. GET|PUT `/files/<id>`) and the content URLs for content operations though (i.e. GET|PUT `/files/<id>/content`)

HTH.

Given this is so old I assume you figured out a solution, or moved on so I am going to close this but please feel free to re-open if you want to discuss (or even better open amn issue against Spring Content)
